# Generated by Django 4.1.4 on 2023-02-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('project_link', models.URLField(max_length=128)),
                ('project_staff', models.ManyToManyField(to='authors.author')),
            ],
        ),
        migrations.CreateModel(
            name='Todo_todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mark_done', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo_app.project')),
            ],
        ),
    ]
